### ISSUE TITLE
Linking qtxmlpatterns fails

### ISSUE THREAD

**Issue by julianscheel** [nezticle/RaspberryPi-BuildRoot#30] opened 2013-01-13 22:44 UTC
With a clean checkout of RaspberryPi-BuildRoot, trying to build the raspberrypi_defconfig I get:
/usr/lib/libstdc++.so: file not recognized: File format not recognized
collect2: ld returned 1 exit status
make[3]: **\* [../../lib/libQt5XmlPatterns.so.5.0.0] Fehler 1
make[3]: Leaving directory `/home/julian/dev/rpi/buildroot/output/rootfs-qt/build/qtxmlpatterns-5.0.0/src/xmlpatterns'

Any ideas what's wrong?

**Comment by nezticle** [comment] 2013-03-24 19:15
I highly suspect this is an error in your build environment, but it is also something I have overlooked in the x86 version of the toolchain.  The thing that is special about the qtxmlpatterns module that would cause it fail is the explicit need for c++ exception handling.

I'm going to close this issue for now, as this is the first time I've seen this reported, and I've not been able to reproduce the issue myself, but if you (or anyone else is having this issue) please re-open and let me know:

What host OS (distro) are you building on?
What host arch are you using (x86 or x86_64)?

**Closed as completed by nezticle** 2013-03-24 19:15 UTC

**Comment by mathben** [comment] 2013-04-10 18:40
I got the same problem on my system.
Arch Linux x86_64. My system is up to date.

But, on my other system, with Fedora 17, it's work.

**Comment by phire** [comment] 2013-12-31 01:12
I'm getting the same kind of problem on Arch Linux x86_64

Looks like the link command is trying to pull in libraries from the host system.

https://gist.github.com/phire/bd484fc3f9ea0a2d5afb/raw/88aa9c93b5f759135bd5032888d740eda61be281/gistfile1.txt

**Comment by phire** [comment] 2013-12-31 01:19
It's looking like it's actually a problem with qmake. It's just that qtxmlpatterns is the first qt lib to be built after qtbase.
